### ISSUE TITLE
handleInputBlur function is not working

### ISSUE THREAD

**Issue by wendylw** [prakhar1989/react-tags#105]
Bind myself function on handleInputBlur, but can not working

**Comment by prakhar1989** [comment]
Hi @wendylw, thanks for opening the issue. If you look at the code for [`handleInputBlur`](https://github.com/prakhar1989/react-tags/blob/9de77b8b9c823a7c498168c4fba6f5db4d34d44d/lib/ReactTags.js#L120-L126), you'll see that the handler is triggered **only when** the textfield is not blank. Did you try out this scenario too?

I've created a webpackbin example for you to see how this works. You can try this here: http://www.webpackbin.com/4yzaRtA9b (click on "Log" button in the menubar to see the output)

**Comment by wendylw** [comment]
Thank you for solution my problem

**Comment by ntsim** [comment]
Hi @prakhar1989, I was playing around with your component today (good work btw) and am surprised by the above `onBlur` behaviour. I'm curious why it shouldn't call the passed `handleOnBlur` if the field is empty?

**Comment by prakhar1989** [comment]
Hi @ntsim, interesting question. I had to check the history to answer that, and it seems the answer lies in [this issue](https://github.com/prakhar1989/react-tags/issues/84) by @Wildhoney. 

The idea behind this change was to automatically convert the text in the input field in case the user tabs over and hence it makes sense to trigger in when the field is non-empty.

Thinking about it now though, I feel the event should always be triggered irrespective of whether the field is empty or not so that it's consistent with what developers expect. The overriding function can then accordingly deal with the empty value scenario. What do you think?

**Comment by ntsim** [comment]
Sounds like a great idea. A validation check in the passed `handleInputBlur` function would be trivial for a developer to implement, but having such a check baked into the API would considerably reduce the amount of control they would have over the behaviour. Generally fewer assumptions are better for building generic components :+1:

**Comment by Wildhoney** [comment]
Will open a PR for the modified behaviour 👍
