### ISSUE TITLE
Make it possible to disable drag and drop

### ISSUE THREAD

**Issue by rikardscm** [prakhar1989/react-tags#23]
It would be nice to have the option of disabling the drag and drop entirely, by passing some prop.

**Comment by prakhar1989** [comment]
@rikardscm Thanks for raising the issue. This does seem a bit hard to do but I'll see what I can do about it. Will keep this open till then.

**Comment by tUrG0n** [comment]
+1 any news @prakhar1989

**Comment by prakhar1989** [comment]
Hey @tUrG0n - sorry for the silence on this. My semester just got over and I was just finishing off a few pending projects. I'll try to get something fixed this week - btw, would you be interested in working up a PR? I'll be happy to help (if required).

**Comment by tUrG0n** [comment]
@prakhar1989 congrats on getting that semester done mate :)
I wish i could work on a PR, but i'm using it as part of a 4 week MVP sprint where i'm building, shipping, getting users and potentially a paying customer :P

**Comment by prakhar1989** [comment]
@tUrG0n Haha! Ok, I'll see on what I can get done! :grinning: 

All the best with your sprint :+1:

**Comment by tUrG0n** [comment]
Thx @prakhar1989  ^^

**Comment by FilipeQ** [comment]
+1

**Comment by rnicholus** [comment]
This is going to be a tough one to fix since react-dnd is used before react-tags is even exported. It is also a key element in one of the exported values (`WithContext`). Breaking changes will be needed to address this. More specifically, a change will need to be made to exports and access to a react-dnd-wrapped react-tags.

Personally, I'd just drop all but a single default export. It's trivial to wrap react-tags in react-dnd (one line of code + an import) if this is the goal of the integration. Furthermore, I'd remove the `Keys` export, since React already normalizes keyboard events by including a `key` property on its `SyntheticEvent` wrapper. That would leave us with a single default export.

**Comment by chmanie** [comment]
@rnicholus Sounds great! I'd also suggest to be able to choose the react-dnd backend to also support touch devices (currently I only have the touch backend installed).

**Comment by rnicholus** [comment]
@chmanie I would expect to remove react-dnd as a dependency entirely. Then you can integrate it however you choose.

**Comment by rnicholus** [comment]
I didn't realize that the internal `<Tag>` component was so dependent on react-dnd. Given that reality, my plan to simply remove react-dnd from the library seems shortsighted. A different solution will be needed it seems.

Perhaps the most recent change described in #56 is sufficient to address the issue described here...

**Comment by tommoor** [comment]
Looks like this should be closed now that https://github.com/prakhar1989/react-tags/pull/58 is merged?

**Comment by rnicholus** [comment]
Perhaps. I'm not sure a more complete solution for making DnD optional is reasonable.
