### ISSUE TITLE
Getting the following run time error with v2.0.2 - Uncaught TypeError: this.refs.input.focus is not a function

### ISSUE THREAD

**Issue by jeseiter** [prakhar1989/react-tags#31]
reactTags.js:56

**Comment by thomasjonas** [comment]
I think the input reference should be wrapped in [ReactDOM.findDomNode](https://facebook.github.io/react/docs/top-level-api.html#reactdom.finddomnode) function since access to the underlying DOM node is needed. See the last paragraph at the [complete example in the React refs docs](https://facebook.github.io/react/docs/more-about-refs.html#a-complete-example)

**Comment by prakhar1989** [comment]
This should be fixed in later releases. Let me know if you're still facing this issue.
