### ISSUE TITLE
Allow to pass style classes as input

### ISSUE THREAD

**Issue by eoinmurray** [prakhar1989/react-tags#32]
Consider something like 

```
<ReactTags
   ...
   classes = {{
      input: 'some-input-class',
      tagInput: 'some-other-class'
   }}
/>
```

I think it would make it much easier to integrated into existing projects that have existing UI packages in place

**Comment by bitdivision** [comment]
I would also appreciate this. Using hard-coded class names is not really ideal in many situations.

I may be extending this module over the coming days. Is it worth making a PR for this?

**Comment by prakhar1989** [comment]
@bitdivision A PR definitely sounds great! The ability to configure class-names with reasonable defaults would be useful. Let me know if you need any help.

**Comment by daamsie** [comment]
I tried this with tagInput: 'form-control' for bootstrap styling. However the tagInput class is not on the actual input itself, but on a div around the input. That to me is not expected behaviour. 

But more importantly it looks like the there isn't currently a way of setting the class of the input itself at the moment.
