### ISSUE TITLE
Unusual size of the package

### ISSUE THREAD

**Issue by Abisar** [prakhar1989/react-tags#385]
For what the this library does it seems like the import size is too large. Is it intended?

![image](https://user-images.githubusercontent.com/18389149/43699585-997db776-9964-11e8-96ce-a80522855bce.png)

**Comment by Bibernull** [comment]
It's because of the libraries' dependencies.
You are probably using react@16.x, which would resolve to 16.4.2 at the moment,
while this project is using exactly react@16.4.1 .
So you end up with 2 react versions packaged in your bundle.

```
  "dependencies": {
    "core-js": "2.5.5",
    "lodash": "4.17.5",
    "prop-types": "15.6.1",
    "react": "16.4.1",
    "react-dnd": "3.0.2",
    "react-dnd-html5-backend": "3.0.2",
    "react-dom": "16.4.1"
  },
```

![image](https://user-images.githubusercontent.com/1374110/43986208-63604c0a-9d0e-11e8-882e-584787745217.png)
