### ISSUE TITLE
Cannot read property 'tagInput' of undefined

### ISSUE THREAD

**Issue by ioterateam** [prakhar1989/react-tags#402]
I follow your installation and demo code, all is good until I run it on my computer, it's give me this error :
![image](https://user-images.githubusercontent.com/29442149/45196784-291f1780-b288-11e8-8637-40dab14b842a.png)
 
What should I do to fix this bug? Please help

**Comment by eliasmamo** [comment]
@ioterateam I have same issue, and in my case problem was in React version higher than 16.3 in which componentWillMount was deprecated. So because of that, classNames prop is not saved to state and when invocing this.state.classNames.tagsInput you get the error you get. Not sure how to solve that, only maybe forking....

**Comment by sbayegan** [comment]
I'm having the same problem. Upgrading react to the latest version doesn't fix it for me!

**Comment by ad1992** [comment]
@sbayegan can you share stackblitz link so I can have a look at your code
