### ISSUE TITLE
Displaying Tags inside input field

### ISSUE THREAD

**Issue by sabinbogati1** [prakhar1989/react-tags#460]
How do I display tags inside input field like this? 
![screenshot from 2019-01-14 23-08-00](https://user-images.githubusercontent.com/15702638/51129041-7e2ff300-1851-11e9-9c97-888de1e35e2f.png)

**Comment by andresmechali** [comment]
This question would be more for StackOverflow.

The tags will not go inside the input field, but you can make it look as if they were. Using classNames prop, you can add custom styles to every part of your autosuggest component. As stated in the documentation, it would be something like this:

    classNames={{
      tags: 'tagsClass',
      tagInput: 'tagInputClass',
      tagInputField: 'tagInputFieldClass',
      selected: 'selectedClass',
      tag: 'tagClass',
      remove: 'removeClass',
      suggestions: 'suggestionsClass',
      activeSuggestion: 'activeSuggestionClass'
    }}

You will therefor need to have a style for those classes. You can have a styles.css file on the same folder and import it (import './styles.css').

There, try playing with the different classes in order to make it look as you desire. For example, the tagsClass would be the one that wraps all the 'input', so you should add some styles like:

    .tagsClass {
      background-color: white;
      padding: 1rem;
      border: solid 0.1rem #d3d3d3;
    }

You can then add something like this to hide the fact that the input is just a part of this:

    .tagInput > input {
      border: none;
    }

And then just keep playing with the classes until it looks like you want.

Hope this helps!
