### ISSUE TITLE
Changing the suggestions prop doesn't trigger an update

### ISSUE THREAD

**Issue by dcsaszar** [prakhar1989/react-tags#508]
Updating the `suggestions` prop (asynchronously) doesn't re-render the suggestions accordingly.

Demo: https://react-tag-input-ncvrjj.stackblitz.io
Here we change the `suggestions` prop 500ms after each input.

### Expected
When changing the `suggestions` prop the Suggestions component rerenders accordingly.

### Actual
The Suggestions component is rerendered eventually, but with an outdated state. (See demo)

### Notes
Last working version: `6.0.2`

**Comment by Johnston1343** [comment]
Having the same issue, reverting to 6.0.2 fixed it for now.

**Comment by davemackintosh** [comment]
Also having this issue with the latest available on npm

**Comment by apepper** [comment]
At least three different people expressed, that they had this issue and that they had to downgrade the version to avoid this bug. So this is definitely not stale!

**Comment by davemackintosh** [comment]
Bump. I don't want this bug getting closed by the Stale Bot.

**Comment by brymon68** [comment]
Having this issue as well. Are we the only people using suggestions?

**Comment by apepper** [comment]
If I'm not mistaken the bug got introduced in d24fe454b53f3e14d505a658e4738d912959d87b, since there is no `UNSAFE_componentWillReceiveProps` any more, that would have updated the state's suggestion based on the new props (/cc @ad1992).

React provides some documentation on how to replace `UNSAFE_componentWillReceiveProps`:
* https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops
* https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

**Comment by dcsaszar** [comment]
See #552 for a fix.

**Comment by brymon68** [comment]
Thank you @dcsaszar and @ad1992. Will we see this in master soon?

**Comment by khoramshahy** [comment]
I also have this problem. why suggestion not update immediately?!
