### ISSUE TITLE
lodash prototype polution advisory

### ISSUE THREAD

**Issue by wei-kortx** [prakhar1989/react-tags#551]
been seeing a high severity vulnerability in my project so finally ran npm audit that lead to this advisory. Is this something to be concerned about? 

https://www.npmjs.com/advisories/1065

![Screen Shot 2019-08-15 at 1 26 32 PM](https://user-images.githubusercontent.com/38010670/63113349-58daa300-bf60-11e9-9f8a-01c83ff4f2be.png)

**Comment by danielgent** [comment]
Hey Prakhar,

First of all, thanks for the great tool, we use it a lot

But because we use it a lot, it's now our last remaining vulnerable dependency

I see that lodash was updated on July 13th but the last version of react-tags was released on 9th March

Do you have an ETA for the next release?  I think it's a pretty low risk that someone could exploit this tag input, but better safe than sorry!

Thanks,
Dan

**Comment by ad1992** [comment]
@wei-kortx @danielgent I will release the next version as soon as https://github.com/prakhar1989/react-tags/pull/548 is merged

**Comment by wviveiro** [comment]
+1

**Comment by ad1992** [comment]
@wei-kortx this is fixed `6.4.1`
