### ISSUE TITLE
Handle ID field that is a number

### ISSUE THREAD

**Issue by dschoon** [prakhar1989/react-tags#593]
I'm receiving the following error because my ID field is an integer and there's no way for me to specify an alternative `idField` prop for me to pass in my `uuid` field name.

```
Uncaught TypeError: t.id.toLowerCase is not a function
    at n.addTag
```

**Comment by ad1992** [comment]
@dschoon this should be fixed in the latest version.

**Comment by bipindubey-technoark** [comment]
Yes i am also facing this problem because when we intergrate api then id is number not a string and they have used string so i am getting same error

**Comment by ad1992** [comment]
`id` is a required field if you are passing tags since https://github.com/prakhar1989/react-tags/releases/tag/v5.0.0 so please make sure you pass id as string

**Comment by bipindubey-technoark** [comment]
when we integrate api with frontend id is always an integer so how can we use it as a string.
I use react for frontend and spring boot for backend so my id field in an integer not an string. you should give an option for use both of them(string and integer) for id field.

**Comment by ad1992** [comment]
> when we integrate api with frontend id is always an integer so how can we use it as a string.
> I use react for frontend and spring boot for backend so my id field in an integer not an string. you should give an option for use both of them(string and integer) for id field or by default should be an integer not a string. By the way who stores id as a string in database???????

I am not sure If I understand you correctly, Id field is kept as a string so that for autosuggestions the suggestions can come up irrespective of case sensitivity and uniqueness is also preserved. You can just pass the id field as what is in your text field or you can share a code sandbox url so I can take a look at what's actually going wrong.

And to answer `By the way who stores id as a string in database???????` there are examples like firebase which store id as a string but that's not the part of this discussion.

**Comment by bipindubey-technoark** [comment]
Yess you are right mongodb, firebase stores id as a string. i m agree with you but most commonly we use integer that i wanted to say. lets leave that... will we get solution for that in upcoming days??

**Comment by ad1992** [comment]
@bipindubey-technoark as I said there are reasons as mentioned above why its a string instead of a number and that's why. 
it was a breaking change.
I am not sure If I will be able to look into it sooner.
But as far as I understand in your case if you are storing the id as an integer fore each. tag,  the change should be to just update those to string or if that's not possible then before passing the prop tags to react tags you can convert the id to string. Is that not possible?

**Comment by bipindubey-technoark** [comment]
Ok
