### ISSUE TITLE
Uncaught TypeError: Cannot set property 'value' of undefined

### ISSUE THREAD

**Issue by kayaelle** [prakhar1989/react-tags#72]
Thanks for this great component.

I'm encountering this error: `"Uncaught TypeError: Cannot set property 'value' of undefined"` in relation to 

```javascript
  // focus back on the input box
	        input.value = "";
	        input.focus();
```

in the `addTag` function.

Think this may be because of 

```javascript
var input = this.refs.input;
```

as I'm also getting this error: `"Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs`. You might be adding a ref to a component that was not created inside a component's `render` method,"

Thanks

**Comment by bigparksh** [comment]
This issue has been at the latest version.

**Comment by prakhar1989** [comment]
Hi @kayaelle, I'm unable to reproduce this error. Can you please clearly outline the steps to do the same?

**Comment by hdriqi** [comment]
Hi @kayaelle, i found out that the problem is because your react and react-dom has different version with the one that react-tags use. So, you will have two react and react dom in your node modules.

The solution is to synchronize your react and react-dom version to the one that react-tags use, which is 15.1, so in your package.json chane your react and react-dom to this one

`   "react": "^15.1.0",
    "react-dom": "^15.1.0",`

**Comment by kayaelle** [comment]
Hi @prakhar1989, Thanks! That fixed it.

**Comment by tommoor** [comment]
I can confirm that I had this same issue and ensuring the react version matched fixed it up. Should be closed as it isn't an issue with react-tags!

**Comment by prakhar1989** [comment]
Thanks everyone!
